### ISSUE TITLE
https://www.antenati.san.beniculturali.it/ark:/12657/an_ua36056322/LeY9lgW

### ISSUE THREAD

**Issue by avitosi** [gcerretani/antenati#12]

**Comment by avitosi** [comment]
Ciao Giovanni!Mi sa che ho fatto un po' di confusione.Parli italiano?Io con l'inglese non ci capisco assolutamenbte nulla!Fammi sapere se possiamo comunicare in italiano.
Un saluto.
Antonio

    Il martedì 31 maggio 2022, 15:38:16 CEST, Giovanni Cerretani ***@***.***> ha scritto:  
 
 


How can I help you?

**Comment by avitosi** [comment]
Buongiorno Giovanni!Volevo solo chiederti se esiste un modo concreto per estrapolare o meglio scaricare i file di ANTENATI in una risoluzione che sia soddisfacente e non il "canvas". Ho letto il tuo messaggio sul gruppo "Amici della genealogia" di facebook ma come vedi devo aver fatto confusione. Ho scaricato quel programma che hai consigliato ma essendo in inglese non ci capisco nulla, non so come si usa e soprattutto non so se funziona ancora allo scopo.Se hai tempo e voglia di illuminarmi a proposito te ne sareri infinitamente grato.Antonio

Inviato da Yahoo Mail su Android 
 
  Il Mer, 1 Giu, 2022 alle 9:18, Giovanni ***@***.***> ha scritto:   


Certo, dimmi pure.

**Comment by gcerretani** [comment]
Prova con le istruzioni semplificate che ho scritto qui: https://github.com/gcerretani/antenati/blob/master/PRINCIPIANTI.md

**Comment by avitosi** [comment]
Intanto grazie, appena provo ti farò sapere se ho avuto successo.Sembra tu sia veramente ferrato in materia; io con l'arte...sui pc ci capisco poco.
Ciao

    Il venerdì 3 giugno 2022 07:45:17 CEST, Giovanni Cerretani ***@***.***> ha scritto:  
 
 


Prova con le istruzioni semplificate che ho scritto qui: https://github.com/gcerretani/antenati/blob/master/PRINCIPIANTI.md
