### ISSUE TITLE
Configuring installation scheme with distutils config files is deprecated

### ISSUE THREAD

**Issue by kordan** [gcerretani/antenati#8]
In Mac OS
cd ~/Desktop
git clone https://github.com/gcerretani/antenati.git antenati
cd antenati
pip3 install -r requirements.txt
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

which python
/usr/bin/python

Quindi sto usando il python preinstallato da apple.
E' un problema del tuo software o del mio mac?

**Comment by gcerretani** [comment]
Credo sia legato a un problema noto di Homebrew:
https://github.com/Homebrew/homebrew-core/issues/76621
